### ISSUE TITLE
how do i build this.. please

### ISSUE THREAD

**Issue by MikkaHYTBG** [BeamMP/BeamMP-Launcher#7]

**Comment by MikkaHYTBG** [comment]
lmao

**Comment by Starystars67** [comment]
Can I presume by the lack of description that the advice / support you require is no longer necessary?

**Comment by MikkaHYTBG** [comment]
oh um, sorry, i do still need help on how to build this

**Comment by MikkaHYTBG** [comment]
im trying to fix some connection issues with v0.23.4.1

**Comment by MikkaHYTBG** [comment]
how did you do it? i cant even get it to build

**Comment by lionkor** [comment]
You do not build it, you download it from https://beammp.com/.

**Comment by MikkaHYTBG** [comment]
yeah but i think that launcher is outdated, so i want to build this one to see if it fixes issues, as the launcher that it publicly available to download is said to support an older version that what this one is supposed to support, so if i can build this one, i can see if it fixes my issues with the older, publicly downloadable one :)

**Comment by lionkor** [comment]
We're hard at work on an update. No ETA yet, though.

**Comment by SirStrategic** [comment]
I was able to create a Visual Studio .sln build using the provided cmake list file. the prequesites required to be installed on pc are zlib and openssl, available at: 

[http://gnuwin32.sourceforge.net/packages/zlib.htm](http://gnuwin32.sourceforge.net/packages/zlib.htm)
[http://gnuwin32.sourceforge.net/packages/openssl.htm](http://gnuwin32.sourceforge.net/packages/openssl.htm)

I then encountered errors in cmake and followed this guide for both zlib and openssl: [https://gist.github.com/davidcorbin/0b13604900089b8fcb28](https://gist.github.com/davidcorbin/0b13604900089b8fcb28)

I have not been able to build the project in visual studio as it keeps crashing as soon as I open it, I have yet to try it with older visual studio versions. This is not a full answer to your question but I hope it helps. 

PS: I don't program much or use cmake much so I don't know much more sorry.

**Comment by Anonymous-275** [comment]
Sorry for the very late reply I just noticed this,
Install cmake on windows with vs2019 with C++ packages and vcpkg from their github then run "vcpkg.exe install zlib:x64-windows-static rapidjson:x64-windows-static openssl:x64-windows-static and discord-rpc:x64-windows-static", after that just simply open x64 Native Tools Command Prompt for VS 2019, and run the cmake commands in the downloaded source code. Said commands can be found in the Github actions script, to link with vcpkg use "-DCMAKE_TOOLCHAIN_FILE=(location of vcpkg)/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static" as a cmake flag. Or I guess you can simply download the exe from the release section since github does all I said for you.
