### ISSUE TITLE
[BUG] Crash on mod download

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP-Launcher#8]
During downloads (not during loading) of mods the Launcher crashes occasionally.

**Comment by snepsnepsnep** [comment]
This appears to happen when the launcher stops receiving data from the server during a mod download, could be down to spotty connection or connection being overloaded on either client or server side.

Also happens if a session reset is called while downloading a mod (for example wanting to cancel the download when joining into a server).

**Comment by Starystars67** [comment]
Maybe we could revise this by allowing it to start the downloads again?
Also on that note maybe we can allow resources to be distributed to the client mid session rather than requiring a client reload on mod change?

**Comment by Starystars67** [comment]
Plus a way to enable and disable mods server side so that we do not have to remove them from the folders?

**Comment by snepsnepsnep** [comment]
> Maybe we could revise this by allowing it to start the downloads again? Also on that note maybe we can allow resources to be distributed to the client mid session rather than requiring a client reload on mod change?

The first step would be having the launcher not crash, otherwise a download can't exactly be restarted without a running launcher, as for the 2nd part I think ages ago jojos had suggested such a feature and it would certainly be neat but fixing existing stuff should probably be higher priority.

Hot-loading/unloading mods would require some work on the lua client side too.

**Comment by lionkor** [comment]
The entire launcher needs a near-rewrite, and then we can look at adding new features. Making sure the launcher doesn't regularly crash and misbehave during usual gameplay should be the highest priority!

**Comment by Starystars67** [comment]
Yeah spot on guys. @lionkor I think its time we intergrate sentry and start getting more data around why all of these issues happen and then start knocking them off from there? Maybe we can try and get a sentry build done over the weekend?

**Comment by Anonymous-275** [comment]
Please reopen if this persits in 2.1.0
